feature/add_theme_custom_icons
vnotex/vnote pull request #2205
Opened 2022-08-07 05:17 UTC by feloxx

add theme custion icons document.

2022-08-08 12:43 UTC, tamlok requested changes

2022-08-08 12:43 UTC, tamlok commented on en_us/docs/Users/Themes and Styles.md
> +- `icons`: customize the icon folder **optional** ；
```suggestion
- `icons`: folder for customized icons (**optional**);
```

2022-08-08 12:43 UTC, tamlok commented on zh_cn/blogs/file/vx.json
> +            "name": "法律.md",
Why

2022-08-08 12:43 UTC, tamlok commented on zh_cn/blogs/vx.json
> +            "name": "file"
Why

2022-08-09 02:46 UTC, feloxx commented on en_us/docs/Users/Themes and Styles.md
> +- `icons`: customize the icon folder **optional** ；
Done.

2022-08-09 02:58 UTC, feloxx commented on zh_cn/blogs/file/vx.json
> +            "name": "法律.md",
Done.

2022-08-09 02:58 UTC, feloxx commented on zh_cn/blogs/vx.json
> +            "name": "file"
Done.

2022-08-09 12:58 UTC, merged